### ISSUE TITLE
macos system not recognized 

### ISSUE THREAD

**Issue by wle0001** [samapriya/geeup#11]
In geeup.py platform.system() returns "Darwin", not "darwin" for mac os 10.14.5

**Comment by samapriya** [comment]
Thank you @wle0001 
I will fix that in next release, simple enough fix to check and to remove case sensitivity for "**Darwin/darwin**". Leaving the issue open till the fix is released

**Comment by samapriya** [comment]
Just released the fix, update to v0.2.7 and should take care of the issue. Closing this for now
