### ISSUE TITLE
No module named 'metadata_loader - geeup 0.2.7

### ISSUE THREAD

**Issue by andrewIndufor** [samapriya/geeup#12]
Hi Samapriya,

I am attempting to run geeup 0.2.7 with python 3.7.4 and experiencing the same metadata_loader issue as matthiasdemuzere previously.

> File "c:\users\ah\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\ah\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\ah\AppData\Local\Continuum\anaconda3\Scripts\geeup.exe\__main__.py", line 5, in <module>
>   File "c:\users\ah\appdata\local\continuum\anaconda3\lib\site-packages\geeup\geeup.py", line 24, in <module>
>     from .batch_uploader import upload
>   File "c:\users\ah\appdata\local\continuum\anaconda3\lib\site-packages\geeup\batch_uploader.py", line 73, in <module>
>     from metadata_loader import load_metadata_from_csv, validate_metadata_from_csv
> ModuleNotFoundError: No module named 'metadata_loader'

Any idea what I am doing wrong here?
Thanks

**Comment by samapriya** [comment]
Hi @andrewIndufor 
Just released v0.2.8, the issue was a small fix that was modified accidentally in v0.2.7. Please upgrade to v0.2.8 in some time using

```
pip install geeup --upgrade
```

I am closing this issue after I tested it out myself, but please feel free to reopen it, if the issue persists

**Comment by matthiasdemuzere** [comment]
Hi, 

I just started using geeup again, and decided to go for a clean install.
Installation was done with: `pip3 install geeup`

When doing `geeup init`, I also get the error message as above.

> Traceback (most recent call last):
  File "/home/demuzmp4/.local/bin/geeup", line 7, in <module>
    from geeup.geeup import main
  File "/home/demuzmp4/.local/lib/python3.6/site-packages/geeup/geeup.py", line 24, in <module>
    from .batch_uploader import upload
  File "/home/demuzmp4/.local/lib/python3.6/site-packages/geeup/batch_uploader.py", line 73, in <module>
    from metadata_loader import load_metadata_from_csv, validate_metadata_from_csv
ModuleNotFoundError: No module named 'metadata_loader'

So I tried ` pip3 install geeup --upgrade`, and afterwards the init again.
Issue persists.

Any ideas?

Versions:
- Python 3.6.9
- geeup-0.2.9

The following dependencies were installed when installing geeup:

> Successfully installed atomicwrites-1.3.0 attrs-19.1.0 beautifulsoup4-4.8.0 cachetools-3.1.1 certifi-2019.9.11 chardet-3.0.4 earthengine-api-0.1.201 future-0.17.1 geeup-0.2.9 google-api-core-1.14.2 google-api-python-client-1.7.11 google-auth-1.6.3 google-auth-httplib2-0.0.3 google-cloud-core-1.0.3 google-cloud-storage-1.19.1 google-resumable-media-0.4.1 googleapis-common-protos-1.6.0 httplib2-0.13.1 idna-2.8 importlib-metadata-0.23 lxml-4.4.1 more-itertools-7.2.0 numpy-1.17.2 oauth2client-4.1.3 packaging-19.2 pandas-0.25.1 pathlib-1.0.1 pluggy-0.13.0 protobuf-3.9.1 psutil-5.6.3 py-1.8.0 pySmartDL-1.3.2 pyasn1-0.4.7 pyasn1-modules-0.2.6 pyparsing-2.4.2 pytest-5.1.2 python-dateutil-2.8.0 pytz-2019.2 requests-2.22.0 requests-toolbelt-0.9.1 retrying-1.3.3 rsa-4.0 selenium-3.141.0 setuptools-41.2.0 six-1.12.0 soupsieve-1.9.3 uritemplate-3.0.0 urllib3-1.25.5 wcwidth-0.1.7 zipp-0.6.0

@andrewIndufor perhaps you can re-open this isue?
