### ISSUE TITLE
Issue with Selenium

### ISSUE THREAD

**Issue by bmcollings** [samapriya/geeup#16]
Hi there, 
I've been having issues with the upload tool in both geeup and ppipe. After going through each prior step it seems that selsetup cannot complete login and is met with this message. 

![image](https://user-images.githubusercontent.com/61722366/75740780-72610200-5d6d-11ea-80ce-6edb239444b0.png)

It seems this is a common issue that has developed recently. I was just wondering if theres any fixes in the works? I've tried using geeadd as well but have run into the same issue.

**Comment by samapriya** [comment]
Hi @bmc921 
Can you test out version 0.3.4. I would recommend trying this in a virtual environment to test it out. Reopen issue or add a comment if the issue persists. It is not a foolproof solution and this may not have a fix that is easy to implement.

**Comment by bmcollings** [comment]
Thanks samapriya. v0.3.4 worked fine. Cheers!
