### ISSUE TITLE
automated authentication?

### ISSUE THREAD

**Issue by matthiasdemuzere** [samapriya/geeup#17]
I now have geeup as part of a larger script chain, which I would like to run in the background.
Yet when executing my geeup command (a zipped shapefile upload), I always have to manually provide my password for the user account I define in the command (--user).

Is there a way to avoid this, and use some sort of automated authentication?

I checked `selsetup`, but when doing this, I get the following error:

> geeup selsetup
> Traceback (most recent call last):
>   File "sel_setup.py", line 7, in <module>
>     from selenium import webdriver
> ImportError: No module named selenium

Is this the way to go, I should I use another approach for the automated authentication (if possible at all)?

**Comment by samapriya** [comment]
This might require you to save your username and password somewhere on your local machine. This is possible but not sure would want to implement it from a security point of view. :) For now, you can literally replace 

[line 95](https://github.com/samapriya/geeup/blob/master/geeup/batch_uploader.py#L95)

or 

[line 72](https://github.com/samapriya/geeup/blob/master/geeup/sel_tuploader.py#L72)

Again not recommended from a security point of view

**Comment by matthiasdemuzere** [comment]
Ok, thanks for your feedback. I'll give it some thought, as I agree this is not the wisest thing to do from a security point of view.

**Comment by samapriya** [comment]
Closing this for now, but will think about this implementation at a later point :)
