### ISSUE TITLE
Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by YUHAN-G** [samapriya/geeup#18]
Hi there,
I was trying to upload my tiff files but got the message below:
![image](https://user-images.githubusercontent.com/62040291/83093224-5eb20700-a0e2-11ea-9a39-af4cea99c4ca.png)
Could you help me to solve this?
Cheers
Hannah

**Comment by samapriya** [comment]
Hi @YUHAN-G 
Can you try installing firefox on your system and trying again?

**Comment by YUHAN-G** [comment]
@samapriya Thanks! It works~
But further, I got the error message below:
![image](https://user-images.githubusercontent.com/62040291/83109805-5dde9c80-a105-11ea-992c-6013dbc8a1c3.png)
I have checked my tiff file names, which only contain letters, numbers, underscores, hyphens.

**Comment by samapriya** [comment]
Could you send me the metadata file you are using? and a filename you are trying to upload?

**Comment by YUHAN-G** [comment]
This is the metadata file, and the tiff file name is the same as the id_no (sorry, the tiff file cannot be uploaded since the format is not allowed)
[prec_metadata.xlsx](https://github.com/samapriya/geeup/files/4693858/prec_metadata.xlsx)

**Comment by samapriya** [comment]
Try this, I simply saved it as a CSV and made sure your system:time_start is a number. I zipped it since they don't allow to attach a CSV file. Unzip and use the CSV file
[prec_metadata.zip](https://github.com/samapriya/geeup/files/4693910/prec_metadata.zip)

**Comment by YUHAN-G** [comment]
There is still an error message like this, I have no idea what does it mean:

invalid syntax (<unknown>, line 2)
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
WARNING:tensorflow:From C:\Users\YUHAN GUO\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

**Comment by samapriya** [comment]
can you upload a single image on google drive and share the link. I can't test without the image

**Comment by YUHAN-G** [comment]
Thanks for your patience, the file can be download via the link below:

https://cloudstor.aarnet.edu.au/plus/s/LfzAbyIhLvWDkXS

**Comment by samapriya** [comment]
Unfortunately, this works for me and I was able to use the image and the metadata to upload the imagery to GEE. My only guess at this point would be that your account might need less secured app to be enabled. I am keeping this issue open till you get to try this out and will close next week since I cannot replicate the issue

I put all the images in a folder and then pointed the metadata.csv file

```
geeup upload --source "folder with tiff images" --dest "users/username/collectioname" --metadata "path to prec_metadata.csv" -u "user@gmail.com"
```

**Comment by samapriya** [comment]
Closing this since unable to replicate the issue

**Comment by YUHAN-G** [comment]
Hi, I have tried to degrade my account security but it seems like not working either. So according to the error description, it has no valid syntax and URL. Do you have any idea where I can check the code? Maybe it is an issue related to the package version?

invalid syntax (, line 2)
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by YUHAN-G** [comment]
Have you done something to the single tif I gave you? or you just upload that single file?

**Comment by samapriya** [comment]
I was able to start uploading it as a collection using the geeup tool. However, the ingest failed with this GEE error. This is not related to geeup but the projection for this image. The entire package is open source and the [uploader code is here](https://github.com/samapriya/geeup/blob/master/geeup/batch_uploader.py)

```
Projection for prec_ITPCAS-CMFD_V0106_B-01_01dy_010deg_197901-197912.tif could not be determined. Make sure both CRS and affine transform are present.
```
