### ISSUE TITLE
Failed to setup selenium

### ISSUE THREAD

**Issue by rmurwat** [samapriya/geeup#19]
When I try to run the following code on a test case of one file: 

geeup upload --source /Users/***username/Dropbox/MSc_Dissertation/GOES-17-CTPhase/Test --dest users/rmurwat/imagecollection -u ***email@gmail.com -m /Users/***username/Dropbox/MSc_Dissertation/GOES-17-CTPhase/metadata.csv

(with my username filled in in the command, of course)

I run into the following error: 

Message: Unable to locate element: //div[@id='identifierNext']/span/span

Failed to setup & use selenium

Any thoughts on what's going wrong?

**Comment by kkraoj** [comment]
I am getting the same error when I tried `geeup selsetup` (before trying anything else).
Error message: 
```
Message: Unable to locate element: //div[@id='identifierNext']/span/span
Failed to setup & use selenium
```
The error occurs exactly after the username is automatically filled on a stackoverflow page in Mozilla Firefox. 

Everything was running fine a few weeks ago and this error occurred just today. So it might be related to some FireFox update?
Any tips to debug is very much appreciated. 
Thanks!

**Comment by steflhermitte** [comment]
Dear @samapriya,

I face the same problem:
`Message: Unable to locate element: //div[@id='identifierNext']/span/span
Failed to setup & use selenium`
running `geeup upload` in a setup that worked perfectly a month ago.

I guess the problem might be the result of an update to the `https://stackoverflow.com/users/signup` page as it the selenium landing page does not seem to contain a _div_ with _id_ 'identifierNext' any longer?

Additionally, I want to express again my gratitude for the development of these GEE-packages. They have smoothened a lot our GEE-workflows.

Thanks again and best regards,
Stef

**Comment by samapriya** [comment]
Thanks everyone will definitely look into this might be over the weekend .

**Comment by kkraoj** [comment]
@steflhermitte was right. The "Next" button on Google signup page is not span resized any more. 
So replacing the following line
```
driver.find_element_by_xpath("//div[@id='identifierNext']/span/span").click()
```
with:
```
driver.find_element_by_xpath("//div[@id='identifierNext']").click()
```
solved the problem for me. 

You can find that line in the respective script that you are running using CTRL+F. 
For e.g., in sel_setup.py, it is on line 37. 
In batch_uploader.py it is on line 253. 
In sel_tuploader.py, it is on line 71.

**Comment by samapriya** [comment]
Yeah, this is the fix I was implementing as well.  But I do want to make sure the Image manifest uploader uses the cloud API functions so will push both those fixes in the next release. Thank you all for your comments and insights :)

**Comment by samapriya** [comment]
Just updated to v0.4.1 which should fix these issues along with some much needed updated. More improvements to come to update codebase.
