### ISSUE TITLE
invalid syntax (<unknown>, line 2), Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

### ISSUE THREAD

**Issue by kaihux** [samapriya/geeup#20]
Hello, when I batch upload GeoTiffs I keep getting errors like the following:

```
New collection users/kh/TahoeLidarCollections created
Processing image 1 out of 58: /Users/kh/Downloads/TahoeLidar/TahoeLidarTif/c_he_39120B24.tif
invalid syntax (<unknown>, line 2)
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Processing image 2 out of 58: /Users/kh/Downloads/TahoeLidar/TahoeLidarTif/c_he_38120G22.tif
invalid syntax (<unknown>, line 1)
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Processing image 3 out of 58: /Users/kh/Downloads/TahoeLidar/TahoeLidarTif/c_he_38119G84s.tif
invalid syntax (<unknown>, line 1)
```

I would appreciate if you could figure out what went wrong and how to solve them. Thanks!

**Comment by samapriya** [comment]
This is usually the case if the session was not authenticated and it cannot get an upload url. Can you confirm you are using geeup v0.4.1? Also that you have less secure apps enabled on your Google account and you don't have any 2 factor authentication? Last but not least the system requires you to have firefox installed for now though gecko driver should simply remove that dependency. Could you run those checks and let me know

**Comment by samapriya** [comment]
Since I have not heard back with additional info, closing this issue for now
