### ISSUE TITLE
Element is not reachable by keyboard

### ISSUE THREAD

**Issue by Pi4ka** [samapriya/geeup#21]
Hi there, 

I was trying to upload images using geeup upload, but after I entered my password, the following error was displayed in the anaconda prompt:
![image](https://user-images.githubusercontent.com/66246001/87218729-e51b6300-c387-11ea-87d5-a37d940481d5.png)
Could you help me to solve this?

Thanks!
Albert

**Comment by samapriya** [comment]
This is an interesting one could you tell me the steps to recreate this error? I have never encountered this. There is no piece of code that looks for a class or an element like that. Try using geeup selsetup to see what is going on and can you confirm you are using geeup v0.4.1?

**Comment by Pi4ka** [comment]
Thanks for your reply!
It seemed that the error were the same when I used geeup selsetup. The firefox were automatically opened and the relevant information were filled until the following page was shown: 
![image](https://user-images.githubusercontent.com/66246001/87262053-1bbdbe80-c4eb-11ea-9435-0ce56ceead4a.png)
After that, the firefox were closed automatically followed by the error being raised:
![image](https://user-images.githubusercontent.com/66246001/87261953-caadca80-c4ea-11ea-88ba-90c638229f24.png)
I checked the package list and confirmed that the version of geeup was v0.4.1. Actually, the geeup getmeta and geeup quota worked well.
Hope this information could help you identify the issue.
Thanks

**Comment by samapriya** [comment]
This is a security popup for trying to log into your Gmail account. Note that this method may not work for GSuite accounts which have a separate password apart from an external password. Unfortunately, this tool may not work for emails not ending with a  @gmail.com domain or where the Gmail login is managed by a gsuite domain. This will not be fixed for now
