### ISSUE TITLE
Path changed to geckodriver

### ISSUE THREAD

**Issue by edtrochim** [samapriya/geeup#22]
Looks like the path changed to the geckodrive.

I got this error:

Downloading from: https://github.com/mozilla/geckodriver/releases/download/0.27.0/geckodriver-0.27.0-linux64.tar.gz
Issues updating with error HTTP Error 404: Not Found

The correct new path appears to be: https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux32.tar.gz

Thanks!

**Comment by samapriya** [comment]
Thanks @edtrochim 
Issue resolved in geeup v0.4.2. Path resolver now resolved from href to get changing paths in release
