### ISSUE TITLE
Issues with delete function

### ISSUE THREAD

**Issue by CGaffey** [samapriya/geeup#25]

**Comment by CGaffey** [comment]
Hi, sorry for the strange history. I thought I got the geeup tool working but I did not.

I've tried multiple variations of this folder's path name but no luck. My original issue was that instead of executing, the terminal spaced down. Please see the screenshot and let me know what I can try. Thank you!!
![image](https://user-images.githubusercontent.com/42742102/91865643-9a0f2500-ec3f-11ea-9421-1b81fd8194b5.png)

**Comment by CGaffey** [comment]
Another example of what I mean incase my explanation wasn't clear:
![image](https://user-images.githubusercontent.com/42742102/91866013-0558f700-ec40-11ea-8869-a41f318ee7f0.png)

**Comment by samapriya** [comment]
Try using a double quote 

```geeup delete "projects/earthengine-legacy/assets/users/clare/SeaIce2"```

and always worst-case scenario try this 

```earthengine rm -r "projects/earthengine-legacy/assets/users/clare/SeaIce2"```

Hope that helps, let me know if it works

**Comment by CGaffey** [comment]
Thanks @samapriya. The second option worked for me.

**Comment by samapriya** [comment]
Thank you @CGaffey 
I will look into the delete function before I release the next version
