### ISSUE TITLE
NameError: global name 'article' is not defined

### ISSUE THREAD

**Issue by tylanderson** [samapriya/geeup#3]
When running geeup update, error is thrown

Traceback (most recent call last):
  File "sel-latest-linux.py", line 34, in <module>
    geckodown(directory=directory)
  File "sel-latest-linux.py", line 15, in geckodown
    container="https://github.com/mozilla/geckodriver/releases/download/"+vr+"/"+str(article.text)
NameError: global name 'article' is not defined
Updated selenium driver for Linux64

Seems to be issue with sel-latest-linux.py due to change in code in v0.1.5

**Comment by samapriya** [comment]
Hey @tylanderson 
Just released a fix, do an upgrade to v0.2.1. Hope that helps :)
