### ISSUE TITLE
Invalid URL 'None': No Schema error caused by incorrect password

### ISSUE THREAD

**Issue by anotohamiprodjo** [samapriya/geeup#31]
While doing a batch upload using geeup, I received the error:

"Invalid URL 'None': No schema supplied. Perhaps you meant http://None?" 

After not finding any help through the solutions online, I found that this issue was caused by using an incorrect password. It didn't occur to me that this was a potential cause for error until I intentionally used the wrong password to troubleshoot and was able to reproduce the error. I did not initially think to test the password because the tool was able to create the image collection with the incorrect password and detect that the image collection exists, but was unable to upload any images.

I just wanted to document this as a known issue to help other users in the future as it seems this issue has come up in the past and was not confirmed as resolved.

**Comment by samapriya** [comment]
Hi @anotohamiprodjo 
Thank you for capturing this. Indeed the tool can create a folder or check collections and tasks because it uses the authentication passed on by the earth engine tool. So the only tool where this fails is the upload tool for uploading images or shapefiles. Thanks for the tag :)
