### ISSUE TITLE
"system:time_start" prior to ~2000 are being added an extra digit when uploading to GEE

### ISSUE THREAD

**Issue by aszinck** [samapriya/geeup#35]
First of all, thank you very much for making this awesome tool. It will definitely save me from a lot of dull uploading time!

I have a set of rasters from 1979 and 2019 which I am uploading to the same image collection. In the metadata CSV file I have added an extra column with a "system:time_start" property. An image from 2019-01-14 has the following `"system:time_start": 1547424000000`, and an image from 1979-01-14 has the following `"system:time_start":285120000000` in the CSV file. However, after using geeup upload, the images from 1979 are being added an extra "0" (285120000000 -> 2851200000000), so they are given a wrong date on the GEE (1979-01-14 -> 2060-05-08). 

Am I doing something wrong, or is there a bug somewhere in the uploading script forcing all `"system:time_start"` properties to have the exact same number of digits?

**Comment by samapriya** [comment]
Hi @aszinck 
The code is designed to actually constrain the numbers to only 10 digits because that is what google allows so I am not sure how you are ending up with 13 digits. Can you upload the CSV file and let me know which version of geeup you are using ? This will help troubleshoot

**Comment by aszinck** [comment]
Yes, of course. 
Here it is.
[metadata_update.csv](https://github.com/samapriya/geeup/files/6434577/metadata_update.csv)

**Comment by samapriya** [comment]
Hey @aszinck 
This sent me down a rabbit hole seems epoch time parsing is hard :) but I think I figured out a fix for now, can you upgrade your install to geeup 0.4.8 and then try again ? I just released it . Hope this helps

**Comment by samapriya** [comment]
Tested this out on a few images with ranges from 1979, closing this for now, feel free to open it , if the problem persists
