### ISSUE TITLE
No output when using zipshape

### ISSUE THREAD

**Issue by eorland** [samapriya/geeup#37]
Hi there, 

Thanks so much for putting together this repo--it's really neat and clearly helps plug a pretty big hole in GEE capabilities. I've gone though the process of installing the software via ```pip``` (but in a ```conda env```) and believe things are up and running. At least, I'm able to generate help commands through the typical ```-h``` options. I can even look at my quota. 

I'm currently working to upload my first shapefile via ```zipshape```, but noticed that whenever I try to run the command, it returns nothing: 

``` geeup zipshape --input . --output .```

After entering this in the command line, the terminal completes the operation silently, and then simply waits for the next command. This happens regardless of the paths I specify. 

A few questions: is this command dependent on Selenium or the cookies option? I checked the documentation and didn't see anything about that. I also have noted that I have the python earth engine api running in my environment just fine. I have tried to set up Selenium support via ```selsetup``` but I'm thrown an error related to not having Firefox on my virtual machine. On my personal machine and its Firefox browser, I am told to use a different browser when I try to run through the login process.

Thanks for any feedback here!

**Comment by samapriya** [comment]
Hi @eorland 
So zipshape simply zips up your shapefile from your source folder to your destination folder. It does not do a recursive search and finds shapefile and additional files like prj , and so on. You have to provide full path to input folder with shapefile files and full path to output folder. 

To actually upload shapefile you would be using the tabup tool and point to the new folder with the zip files hope that helps. 

Also if you use the cookies method you do not need selenium at all so I would recommend that way for your setup

**Comment by eorland** [comment]
Ah, I see I must have been misreading the documentation for the tool. I'll close this for now and let you know if I run into any more issues. Thanks for the help here!

**Comment by samapriya** [comment]
Also I would use this for updated docs
https://samapriya.github.io/geeup/

**Comment by eorland** [comment]
Yes, thank you for the feedback! Hmm, I found that the cookie method worked on my local machine. Now I'm using my own inputs for the specified sample script you provided: 

```geeup tabup --source "full path to folder with Zipped Shapefiles" --dest "Full path for upload to Google Earth Engine, e.g. users/pinkiepie/foler" --user "email@domain.com authenticated and used with GEE" --method "cookies"```

Everything succeeds and I can even create a new asset folder. Interestingly, I am then told that all the assets are already copied, when they are not on there or in the process of uploading. In other words, the newly created folder is empty. Is there something I'm doing wrong on my end?

note: I zipped the shapefiles myself.

**Comment by samapriya** [comment]
You can send me a few of the zipped shape files if you would like but it would not be possible to test for an issue without that

**Comment by eorland** [comment]
Great, I will do a few more test cases and might try to do that. With an upcoming project deadline, I am needing to temporarily change tasks but hope to return to this next week. Thanks for all the info so far.

**Comment by eorland** [comment]
Shot you an email about two weeks ago with some files. Thanks for any assistance!

**Comment by samapriya** [comment]
Seems the files worked for me I was able to upload the files to a folder you can check the asset and the script here
https://code.earthengine.google.com/1eaed4a12cbd45d573dc4d24357c1762

At this point I am unable to replicate your issue

**Comment by eorland** [comment]
Thank you for taking the time to check this out. I wonder if it has to do with how I installed this repo via pip within my conda environment. Even though everything built correctly and I was able to connect with my account, I wonder if there is a hidden compatibility issue. I might try a few other strategies but it appears this issue is only on my end. Thanks for the guidance.
