### ISSUE TITLE
when using geeup, reports error local variable 'gsid' referenced before assignment

### ISSUE THREAD

**Issue by wanyue92** [samapriya/geeup#38]
when I upload these tif files with metadata generated in the same folder, it reports that local variable referenced before assignment. would you help indicate what is the reason of the error? 
![微信图片_20210618114932](https://user-images.githubusercontent.com/54383454/122503572-46819280-d02b-11eb-819d-c1eca9424f98.png)

![微信图片_20210618114939](https://user-images.githubusercontent.com/54383454/122503601-526d5480-d02b-11eb-9761-f451730d038d.png)

**Comment by scoffiel** [comment]
I'm having the same issue and opened a new issue. Any idea what was causing this?

**Comment by wanyue92** [comment]
Have you got a GCS bucket and a registered GCS account?&nbsp; I think it is the problem of not having this. Anyway, using GCS directly uploading is easy and you can try.&nbsp;


 
---Original---
From: "Shane ***@***.***&gt;
Date: Sat, Jul 3, 2021 07:40 AM
To: ***@***.***&gt;;
Cc: "State ***@***.******@***.***&gt;;
Subject: Re: [samapriya/geeup] when using geeup, reports error local variable 'gsid' referenced before assignment (#38)




 
I'm having the same issue and opened a new issue. Any idea what was causing this?

**Comment by scoffiel** [comment]
Oh ok thanks! I have a GCS account but no buckets. I will try this next week

Update: actually the issue was just that I didn't include the argument -u yourusername@gmail.com
