### ISSUE TITLE
Upload error "local variable 'gsid' referenced before assignment"

### ISSUE THREAD

**Issue by scoffiel** [samapriya/geeup#39]
Hi, thanks for building this tool! I got it installed and have the cookies and metadata set up. When using the geeup upload command for a folder of tifs I'm getting

```
Processing image 1 out of 36: [path]
local variable 'gsid' referenced before assignment
Upload of [image] has failed
```

I've tried this on a couple unrelated datasets and am getting the same error. Any ideas what I could be doing wrong?

**Comment by samapriya** [comment]
Hi @scoffiel 
Could you paste the exact command you are using for the upload process. I would need that to get some clues

**Comment by scoffiel** [comment]
`geeup upload --source /Users/scoffiel/fire/landcover/ARD_h01v05 --dest projects/ca-ecs/fractionalCover/tmp -m /Users/scoffiel/fire/landcover/metadata.csv --method cookies`

Output:
```
Collection projects/ca-ecs/fractionalCover/tmp already exists
Processing image 1 out of 36: /Users/scoffiel/fire/landcover/ARD_h01v05/ARD_h01v05_1998.tif
local variable 'gsid' referenced before assignment
Upload of ARD_h01v05_1998 has failed.
Processing image 2 out of 36: /Users/scoffiel/fire/landcover/ARD_h01v05/ARD_h01v05_1999.tif
local variable 'gsid' referenced before assignment
Upload of ARD_h01v05_1999 has failed.
Processing image 3 out of 36: /Users/scoffiel/fire/landcover/ARD_h01v05/ARD_h01v05_1989.tif
local variable 'gsid' referenced before assignment
Upload of ARD_h01v05_1989 has failed.
```
... and so on for 36 tif files.

Let me know if you have any ideas as to what's going on. Thanks

**Comment by samapriya** [comment]
Can you pass the username in the command apart from everything else in the setup? Let me know how that goes 

```
geeup upload --source /Users/scoffiel/fire/landcover/ARD_h01v05 --dest projects/ca-ecs/fractionalCover/tmp -m /Users/scoffiel/fire/landcover/metadata.csv --method cookies -u yourusername@gmail.com
```

**Comment by scoffiel** [comment]
That solved it! I forgot to include the user argument which was a silly mistake. Thanks for your help
