### ISSUE TITLE
"stty -icanon" command does not work in Mac's Zsh

### ISSUE THREAD

**Issue by jiachengzhao** [samapriya/geeup#41]
Hi, @samapriya,
I am currently using a Mac for uploading images to my GEE assets. I follow the instruction [here](https://samapriya.github.io/geeup/projects/cookies_setup/) to set up my cookies. However, after I type in `stty -icanon` in terminal, I still can not paste complete cookies into the terminal (please see the screenshot below).

![image](https://user-images.githubusercontent.com/44634091/135007531-2f041560-68e0-4871-8ed5-70ff4ca7e0ee.png)

Information about my machine:

> system: macOS Big Sur version 11.6
> terminal: The Z shell of Mac (also known as zsh)

Thank you very much for your time.

**Comment by samapriya** [comment]
This is an interesting one , since this is terminal-specific and not an app issue I might have to dig into this later but I will think of a workaround in the meantime

**Comment by jiachengzhao** [comment]
Hi @samapriya,
I just found a workaround for Mac users. After changing the default login shell from /bin/zsh to /bin/sh, the command `stty -icanon` works as expected. Now I can set up my cookies perfectly.

**Comment by samapriya** [comment]
This is great, thank you for letting me know. I might just add your workaround to the read me to help other users too :) closing this ticket for now
