### ISSUE TITLE
Parameter "name" value "projects/myproject/assets" does not match the pattern "^projects/[^/]+/assets/.*$"

### ISSUE THREAD

**Issue by wuhan12345** [samapriya/geeup#47]
Dear Samapriya,

Recently, I used your excellent geeup package to upload GeoTIFF images from the local machine to the GEE asset.  I tried to use the geeup upload function "geeup upload --source "full path to folder with GeoTIFFs" --dest "Full path for upload to Google Earth Engine" --metadata "Full path for metadata file.csv" --user "email@domain.com". 

It works when I upload the GeoTIFF images to the standard legacy folder. But when I replaced the destination folder with my Cloud Projects. For example, I set "projects/ee-wsh-project01/assets/test" as the destination folder. It reports the following error 
TypeError: Parameter "name" value "projects/ee-wsh-project01/assets" does not match the pattern "^projects/[^/]+/assets/.*$"

I have no idea why this error happens. Do you have any suggestions for this issue?

Thank you

**Comment by samapriya** [comment]
I have identified the fix will be pushing it in next release

**Comment by samapriya** [comment]
just pushed the update v0.5.4 has the fix for the issue you were having. Closing this issue but feel free to reopen if there are issues

https://pypi.org/project/geeup/

**Comment by wuhan12345** [comment]
Dear Samapriya,

It works now. Thanks so much for your help and great contributions to the community. 

Best regards
Shengbiao Wu
The University of Hong Kong
