### ISSUE TITLE
Max retries exceeded with url: /assets/upload/geturl

### ISSUE THREAD

**Issue by Liuyi0205** [samapriya/geeup#49]
Dear Samapriya,

Recently, I try to upload images using the geeup packages you developed. But when I tried to use the geeup upload function "geeup upload --source "full path to folder with GeoTIFFs" --dest "Full path for upload to Google Earth Engine" --metadata "Full path for metadata file.csv" --user "[email@domain.com](mailto:email@domain.com)", it displays the following bug: "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='code.earthengine.google.com', port=443): Max retries exceeded with url: /assets/upload/geturl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B2BE8FD310>: Failed to establish a new connection: [WinError 10060]" .

I can't solve it, do you have any solutions?

Thanks,
Yi Liu

**Comment by samapriya** [comment]
Not a 100% sure here you might be behind a firewall so this might be failing as a result, unable to replicate this

**Comment by samapriya** [comment]
Since there is no update on this issue closing for now
