### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by matthiasdemuzere** [samapriya/geeup#5]
Hi,

I am currently trying to run this tool on my ubuntu 18.03 64bit python 3.6.7 machine, on the command line: `python3 geeup.py`

When doing so I get the following error:

> Traceback (most recent call last):
>   File "geeup.py", line 156, in <module>
>     main()
>   File "geeup.py", line 153, in main
>     args.func(args)
> AttributeError: 'Namespace' object has no attribute 'func'

Printing args in geeup.py provides: Namespace()

Any idea why that is?

**Comment by samapriya** [comment]
Can you try installing the package using 

```pip install geeup```

Then call a ```geeup -h``` in your terminal. I am not sure because args.func(args) is available when parsing args after parser.pargse_args. If that works then I think I know how to fix it in the next release and can apply that.

**Comment by matthiasdemuzere** [comment]
when I use `pip install geeup` and do `geeup -h`, I get the following error:

```
Traceback (most recent call last):
  File "/home/demuzmp4/anaconda3/envs/py367/bin/geeup", line 6, in <module>
    from geeup.geeup import main
  File "/home/demuzmp4/anaconda3/envs/py367/lib/python3.6/site-packages/geeup/geeup.py", line 24, in <module>
    from .batch_uploader import upload
  File "/home/demuzmp4/anaconda3/envs/py367/lib/python3.6/site-packages/geeup/batch_uploader.py", line 73, in <module>
    from metadata_loader import load_metadata_from_csv, validate_metadata_from_csv
ModuleNotFoundError: No module named 'metadata_loader'
```

**Comment by samapriya** [comment]
Thanks @matthiasdemuzere 
I will work on these issues this weekend and should have a new release that fixes this concern. Since I now know that you are using python 3.6 , I can test out specific environments

**Comment by samapriya** [comment]
Hi @matthiasdemuzere 
So the first error is related to the fact that you did not pass any arguments meaning
instead of trying ```python3 geeup.py``` try ```python3 geeup.py -h```. It needs args to be valid during parsing

I fixed the issue with metadata loader in release 0.2.3. If you are going this way try uninstalling geeup and reinstalling geeup 0.2.3. 

I hope this resolves both your issues
