### ISSUE TITLE
Building cache

### ISSUE THREAD

**Issue by jiachengzhao** [samapriya/geeup#50]
Hi samapriya, recently I change from a Mac platform to a PC. I can successfully install geeup on PC but everytime I issue a command (e.g., `geeup -h`), it will keep building cache, which takes a long time. Since all the requirements are satisfied, so might this be a bug?

![image](https://user-images.githubusercontent.com/44634091/190658931-7b4410d9-aef8-4708-bf20-6e0760f99756.png)

Thank you very much for your time!

**Comment by samapriya** [comment]
This is interesting I might need time to reproduce it

**Comment by samapriya** [comment]
This has been fixed, and the need for cache removed for now
