### ISSUE TITLE
FutureWarning on Deprecated Item

### ISSUE THREAD

**Issue by JYAnchang** [samapriya/geeup#53]
This is a great tool! Appreciate all your great work. My first time using it and hoping it can save me countless hours of work. In the event I wrongly followed the instructions, please kindly point it out.

**Summary:**
I get a FutureWarning about deprecated items when using gee upload command. Can't tell if the upload is really happening or not.

**Desired Outcome**
Upload files without warning and be able to track progress

**Steps to Reproduce**
1) Have a folder of 197 high resolution  geotifs to upload to a GEE image collection (93GB total)

2) Using conda env with python 3.9, gee authentication, geeup, cookies have been set up as instructed on the Github page.

3) metadata csv with with image id_no and timestamp created using previous notebook example: _https://colab.research.google.com/gist/JustinWenzhaoLi/cefc77ccb63557e1a448e04691e9157a/gee_imagecollection_upload_metadata_generater.ipynb_

4) geeup upload command in anaconda CLI as follows (using the actual paths on my local machine):
geeup upload --source D:\worldview_data\esa_latest\TIFS --dest projects/ee-slnmsu-vhr/assets/esa_images -m D:\worldview_data\esa_latest\meta_data.csv --user savannalabnmsu@gmail.com --nodata 0 --pyramids MEAN

 The following message get printed repeatedly for every image I think.
 _C:\Users\anchang\Anaconda3\envs\gee_projects\lib\site-packages\geeup\batch_uploader.py:167: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead. for ind, val in dd.iteritems():_

In my experience, future deprecation messages usually do not prevent execution,  but GEE task manager is not show anything being ingested so far (been running for about 1 hour). May be I need to wait longer but I thought I'd bring this your notice.

**Comment by samapriya** [comment]
This should be fixed now
