### ISSUE TITLE
pd.Series.iteritems deprecated in pandas 2.0.0

### ISSUE THREAD

**Issue by vergauwenthomas** [samapriya/geeup#55]
When running geeup upload i get the following error:
_'Series' object has no attribute 'iteritems'_

This comes from here:
https://github.com/samapriya/geeup/blob/ab9bfd40e65a3c3c31fb1a2cb77b5324e00958ac/geeup/batch_uploader.py#L167
because iteritems is deprecated in pandas 2.0.0.

Fix:
`for ind, val in dd.items():`

**Comment by samapriya** [comment]
Thank you this has been fixed in version 0.6.5
