### ISSUE TITLE
Silenty fails to download driver

### ISSUE THREAD

**Issue by okhoma** [samapriya/geeup#6]
Could not download driver using `geeup update` but printed "Updated selenium driver for Windows64":

```
(E:\conda\env\gee) E:\ndvi>geeup update
Downloading from: https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-win64.zip
The read operation timed out
Updated selenium driver for Windows64

```

The script should verify if driver was actually downloaded.

**Comment by samapriya** [comment]
Hey @okhoma 
just fixed, update to v0.2.4
