### ISSUE TITLE
Uploading .tifs without metadata?

### ISSUE THREAD

**Issue by adrianom-gh** [samapriya/geeup#7]
Hi @samapriya,

Was curious to know the reason behind making metadata a required input when uploading as an asset. I only need to upload .tifs that do not have metadata.

**Comment by samapriya** [comment]
Hi Adrianom,
The upload tool now uses the manifest upload method, and hence needs metadata, even if the metadata is nothing with a list of the names of the files as system:id. I will keep this issue open with the possibility of uploading without metadata using simple upload.

**Comment by mgmanalili** [comment]
Hi @samapriya ,
Can you provide me a sample metadata file? I also want to upload a raw TIF without metadata. Thanks. I am not sure if getting GDALINFO and paste it in a text file would work.

Thanks!

**Comment by samapriya** [comment]
Hi @mgmanalili and @adrianom-gh 
I think I took your idea about creating metadata by using simple gdal and I am going to create and release that as part of the next version of the tool. A bare minimum metadata file can be something as simple as just the filenames in rows with id_no as header. Do not use the file extension in the id_no column. it assumes all files are GeoTiffs. I am testing a tool currently to do this for all rasters in a folder using the GDAL based simple metadata tags.

id_no
L15-2673E-2340N
L15-2673E-2341N
L15-2673E-2342N
L15-2673E-2343N

**Comment by samapriya** [comment]
Hi @adrianom-gh and @mgmanalili 
Instead of uploading rasters without metadata, this updates v0.2.5 includes a general metadata creator using gdal info and metadata tags. This way you can create metadata for any set of rasters and then upload. I wanted to keep the manifest method standard for image upload. Closing the issue as a result of the update.
