### ISSUE TITLE
invalid syntax and Nonetype error

### ISSUE THREAD

**Issue by Vindicare007** [samapriya/geeup#8]
Hello first off thank you for making this package I have been searching for and wide for something like this! 

I'm trying to batch upload some shapefiles to the google earth engine. However I'm having some difficulty with it and I suspect that I'm doing something wrong.
I installed geeup and also updated it before running these commands.

I first tried this command (obviously with my real path info):
`geeup seltabup --source /home/path/my/zippedShapefiles --dest users/usernameGEE/Folder 
`This returns a nontype error (TypeError: object of type 'NoneType' has no len())

After this command I thought the files were not correct however the zipfile contains:
.shp .dbf .prj .shx files so that should be okay.

Afterwards I added the user credentials:
`geeup seltabup --source /home/path/my/zippedShapefiles --dest users/usernameGEE/Folder --user MyEmail@Gmail.com
`This however gives me the ''invalid syntax (<unknown>, line 2)'' error.

In any case the folder does get created in my google earth engine assests, however the files are not being uploaded because of the errors I think.

What am I doing wrong?

**Comment by samapriya** [comment]
Hi @Vindicare007 
Could you provide some more details to help understand the issue

1. **selenium will only work on systems that have a display attached and not in a headless state, so it won't run on a machine without a display or over ssh.**

2. **feel free to drop a small zip file for me to test, and please make sure that two-factor authentication is not turned on your** [Gmail and also that less secure apps](https://support.google.com/accounts/answer/6010255?hl=en) 

Hopefully, this will help me track down the issue.

Sam

**Comment by Vindicare007** [comment]
Hello Sam,

Thank you for responding to my issue(s). 
To answer your first question, I'm running it on my laptop (t460s, os:ubuntu)

Secondly, I will add two zipfiles. This one (not processed by Zipshape):
[EA_201001_CS.zip](https://github.com/samapriya/geeup/files/3382111/EA_201001_CS.zip)
and another one (different shapefile processed by the geeup zipshape function):
[ET_LHZ_2009.zip](https://github.com/samapriya/geeup/files/3382115/ET_LHZ_2009.zip)
In both cases it didn't work. I'm curious whether it will work for you.

With regards,
Vindicare

**Comment by samapriya** [comment]
Hi @Vindicare007 
I was able to upload your zip files using geeup. Another thing I would try is to put the path in double quotes and before that do a geeup update. This refreshes the selenium drivers used.

**Comment by Vindicare007** [comment]
Hello, I have tried to do what you said.

This time I have tried it on my windows computer:
`geeup seltabup --source "C:\Users\Vindicare\Downloads\FolderwithShapefiles\" --dest users/username/testing2 -u MyEmail@gmail.com
`

With the path in double quotes. It only returns me the error: the following arguments are required: --dest

I also updated it. If I may ask what is the exact command that you type, which worked in your case?

Since doing this after updating and disabeling 2fa still gives me the invalid syntax at line 2:
`geeup seltabup --source C:\Users\Vindicaare\Downloads\FolderwithShapefiles\ --dest users/usernamegoogle/testing2 -u Myemail@gmail.com
`

EDIT:
I managed to get it working on my linux computer. I have turned off, 2fa and the less secure apps permission. I think that solved it for my laptop.

It still however doesn't work for my windows pc, which gives me the following error (it Command 'earthengine upload table --asset_id users/username/testing2/EA_201001_CS gs://earthengine-uploads/lOsfcfOtBJYdLWjd/EA_201001_CS.zip' returned non-zero exit status 1.)

Nevertheless it works on my laptop, so that is  a good thing. Not sure though wat the error means on my windows pc though

**Comment by samapriya** [comment]
Hi @Vindicare007 
I think I figured out the issue for windows pc. Removed the last back slash in your source folder path as below. In windows, I think it escapes differently even when without a quote, this should work in theory, let me know and I can close the issue. The non-zero exit status is interesting and should not happen

```geeup seltabup --source "C:\Users\Vindicare\Downloads\FolderwithShapefiles" --dest users/username/testing2 -u MyEmail@gmail.com```

**Comment by samapriya** [comment]
Since I did not hear back, am hoping this issue has been resolved, closing this issue now
