### ISSUE TITLE
Error in upload

### ISSUE THREAD

**Issue by mgmanalili** [samapriya/geeup#9]
I got this error:

`os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

I ran the following command:

geeup upload --source '/Users/michael/GEO/floods_database/in_rast_raw/' --dest 'users/wfphqgis/LULC' -u 'wfp.hq.gis@gmail.com' -m '/Users/michael/GEO/floods_database/in_rast_raw/meta.csv'

**Comment by samapriya** [comment]
If you installed geeup for the first time, you have to run the command

```geeup update``` 

This will download the geckodriver needed to run selenium and use the tool

P.S I am planning to change this to ```geeup init``` to represent initialization

**Comment by mgmanalili** [comment]
Dear Roy,

Thanks for your quick response. Apparently my OS is not supported (MAC) and
this is the reason I am getting this error. Is there going to be a support
for OSX soon? Let me know. Thanks!

*"Architecture not recognized"*

def update():
if str(platform.system()) =="Windows":
os.system("python sel-latest-win.py")
elif str(platform.system()) =="Linux":
os.system("python sel-latest-linux.py")
else:
print("Architecture not recognized")
